
// fetch('../data/race_calendar.json')
// .then(response => {
// if (!response.ok) {
//     throw new Error('Error al cargar el archivo JSON');
// }
// return response.json();
// })
// .then(data => {
// }
// )
// .catch(error => {
//     console.error('Error:', error);
// }); 

var race_calendar = [
    {
        "gp_name": "Gran Premio de Bahréin",
        "track_name": "Circuito Internacional de Bahréin",
        "id_card": "bahrein",
        "straights": "64%",
        "slow_turns": "15%",
        "medium_turns": "15%",
        "fast_turns": "6%",
        "boxText": "• Este circuito en el desierto alberga la primera carrera de la temporada. Es conocido por sus largas rectas y zonas de frenado brusco.",
        "calendar_date": "2023-03-05",
        "img_country": "bahrein",
        "img_track": "bahrein",
        "fecha": "2023-03-05T22:00:00Z",
        "fastest_lap": "1:31.447",
        "fastest_lap_driver": "Pedro Martínez de la Rosa",
        "track_length_km": "5.412",
        "last_5_winners": ["Max Verstappen", "Lewis Hamilton", "Lewis Hamilton", "Charles Leclerc", "Sebastian Vettel"],
        "last_5_poles": ["Charles Leclerc", "Max Verstappen", "Lewis Hamilton", "Charles Leclerc", "Sebastian Vettel"],
        "fecha": "2023-03-12T22:00:00Z"
    },
    {
        "gp_name": "Gran Premio de Arabia Saudí",
        "track_name": "Circuito de Yeda",
        "id_card": "arabia",
        "straights": "48%",
        "slow_turns": "",
        "medium_turns": "",
        "fast_turns": "",
        "boxText": "• Este trazado urbano alberga el Gran Premio de Arabia Saudí. Es considerado un circuito urbano rápido con curvas rápidas y desafiantes, y largas rectas. Destaca por su estrechez y nocturnidad.",
        "calendar_date": "2023-03-19",
        "img_country": "arabia",
        "img_track": "arabia",
        "fastest_lap": "1:31.634",
        "fastest_lap_driver": "Lewis Hamilton",
        "track_length_km": "6.174",
        "last_5_winners": ["Lewis Hamilton", "Max Verstappen"],
        "last_5_poles": ["Lewis Hamilton", "Max Verstappen"],
        "fecha": "2023-03-19T22:00:00Z"
    },
    {
        "gp_name": "Gran Premio de Australia",
        "track_name": "Circuito de Albert Park",
        "id_card": "australia",
        "straights": "60%",
        "slow_turns": "15%",
        "medium_turns": "15%",
        "fast_turns": "10%",
        "boxText": "• Ubicado en Melbourne, este circuito urbano ofrece una combinación de rectas rápidas y curvas técnicas.",
        "calendar_date": "2023-04-02",
        "img_country": "australia",
        "img_track": "australia",
        "fastest_lap": "1:20.260",
        "fastest_lap_driver": "Charles Leclerc",
        "track_length_km": "5.303",
        "last_5_winners": ["Charles Leclerc", "Lewis Hamilton", "Sebastian Vettel", "Sebastian Vettel", "Lewis Hamilton"],
        "last_5_poles": ["Charles Leclerc", "Lewis Hamilton", "Lewis Hamilton", "Sebastian Vettel", "Lewis Hamilton"],
        "fecha": "2023-04-02T22:00:00Z"
    },
    {
        "gp_name": "Gran Premio de Mónaco",
        "track_name": "Circuito de Mónaco",
        "id_card": "monaco",
        "straights": "40%",
        "slow_turns": "40%",
        "medium_turns": "15%",
        "fast_turns": "5%",
        "boxText": "• Conocido por su glamour y dificultad, Mónaco es uno de los circuitos más icónicos y exigentes del calendario.",
        "calendar_date": "2023-05-28",
        "img_country": "monaco",
        "img_track": "monaco",
        "fastest_lap": "1:14.260",
        "fastest_lap_driver": "Max Verstappen",
        "track_length_km": "3.337",
        "last_5_winners": ["Max Verstappen", "Lewis Hamilton", "Daniel Ricciardo", "Sebastian Vettel", "Lewis Hamilton"],
        "last_5_poles": ["Max Verstappen", "Charles Leclerc", "Lewis Hamilton", "Sebastian Vettel", "Lewis Hamilton"],
        "fecha": "2023-05-28T22:00:00Z"
    },
    {
        "gp_name": "Gran Premio de Miami",
        "track_name": "Circuito Internacional de Miami",
        "id_card": "miami",
        "straights": "52%",
        "slow_turns": "20%",
        "medium_turns": "20%",
        "fast_turns": "8%",
        "boxText": "• Este circuito nuevo y emocionante se desarrolla en las calles de Miami, con un diseño que busca desafiar a los pilotos con una combinación de velocidad y técnica.",
        "calendar_date": "2023-05-07",
        "img_country": "miami",
        "img_track": "miami",
        "fastest_lap": "1:13.078",
        "fastest_lap_driver": "Valtteri Bottas",
        "track_length_km": "4.361",
        "last_5_winners": ["Max Verstappen", "Lewis Hamilton", "Lewis Hamilton", "Sebastian Vettel", "Lewis Hamilton"],
        "last_5_poles": ["Max Verstappen", "Lewis Hamilton", "Lewis Hamilton", "Sebastian Vettel", "Lewis Hamilton"],
        "fecha": "2023-06-18T22:00:00Z"
    },
    {
        "gp_name": "Gran Premio de Emilia-Romaña",
        "track_name": "Autódromo Enzo e Dino Ferrari",
        "id_card": "emilia_romagna",
        "straights": "50%",
        "slow_turns": "20%",
        "medium_turns": "20%",
        "fast_turns": "10%",
        "boxText": "• También conocido como Imola, este circuito histórico es conocido por su flujo rápido y técnico.",
        "calendar_date": "2023-05-21",
        "img_country": "emilia_romagna",
        "img_track": "emilia_romagna",
        "fastest_lap": "1:13.078",
        "fastest_lap_driver": "Valtteri Bottas",
        "track_length_km": "4.361",
        "last_5_winners": ["Max Verstappen", "Lewis Hamilton", "Lewis Hamilton", "Sebastian Vettel", "Lewis Hamilton"],
        "last_5_poles": ["Max Verstappen", "Lewis Hamilton", "Lewis Hamilton", "Sebastian Vettel", "Lewis Hamilton"],
        "fecha": "2023-06-18T22:00:00Z"
    },
    {
        "gp_name": "Gran Premio de Canadá",
        "track_name": "Circuito Gilles Villeneuve",
        "id_card": "canada",
        "straights": "55%",
        "slow_turns": "20%",
        "medium_turns": "15%",
        "fast_turns": "10%",
        "boxText": "• Este circuito en Montreal es conocido por sus largas rectas y chicanes técnicas, además del famoso Muro de los Campeones.",
        "calendar_date": "2023-06-18",
        "img_country": "canada",
        "img_track": "canada",
        "fastest_lap": "1:13.078",
        "fastest_lap_driver": "Valtteri Bottas",
        "track_length_km": "4.361",
        "last_5_winners": ["Max Verstappen", "Lewis Hamilton", "Lewis Hamilton", "Sebastian Vettel", "Lewis Hamilton"],
        "last_5_poles": ["Max Verstappen", "Lewis Hamilton", "Lewis Hamilton", "Sebastian Vettel", "Lewis Hamilton"],
        "fecha": "2023-06-18T22:00:00Z"
    },
    {
        "gp_name": "Gran Premio de España",
        "track_name": "Circuito de Barcelona-Cataluña",
        "id_card": "espana",
        "straights": "58%",
        "slow_turns": "20%",
        "medium_turns": "15%",
        "fast_turns": "7%",
        "boxText": "• Este circuito es conocido por su combinación de curvas rápidas y técnicas, además de ser una prueba importante para los equipos debido a su variado diseño.",
        "calendar_date": "2023-06-04",
        "img_country": "espana",
        "img_track": "espana",
        "fastest_lap": "1:13.078",
        "fastest_lap_driver": "Valtteri Bottas",
        "track_length_km": "4.361",
        "last_5_winners": ["Max Verstappen", "Lewis Hamilton", "Lewis Hamilton", "Sebastian Vettel", "Lewis Hamilton"],
        "last_5_poles": ["Max Verstappen", "Lewis Hamilton", "Lewis Hamilton", "Sebastian Vettel", "Lewis Hamilton"],
        "fecha": "2023-06-18T22:00:00Z"
    },
    {
        "gp_name": "Gran Premio de Austria",
        "track_name": "Red Bull Ring",
        "id_card": "austria",
        "straights": "70%",
        "slow_turns": "10%",
        "medium_turns": "15%",
        "fast_turns": "5%",
        "boxText": "• Este corto pero rápido circuito es conocido por sus cambios de elevación y curvas técnicas.",
        "calendar_date": "2023-07-02",
        "img_country": "austria",
        "img_track": "austria",
        "fastest_lap": "1:05.619",
        "fastest_lap_driver": "Carlos Sainz",
        "track_length_km": "4.318",
        "last_5_winners": ["Max Verstappen", "Charles Leclerc", "Max Verstappen", "Max Verstappen", "Valtteri Bottas"],
        "last_5_poles": ["Max Verstappen", "Max Verstappen", "Lewis Hamilton", "Charles Leclerc", "Valtteri Bottas"],
        "fecha": "2023-07-02T22:00:00Z"
    },
    {
        "gp_name": "Gran Premio de Gran Bretaña",
        "track_name": "Circuito de Silverstone",
        "id_card": "gran_bretana",
        "straights": "65%",
        "slow_turns": "10%",
        "medium_turns": "15%",
        "fast_turns": "10%",
        "boxText": "• Conocido por sus curvas rápidas y fluyentes, Silverstone es uno de los circuitos más históricos de la F1.",
        "calendar_date": "2023-07-09",
        "img_country": "gran_bretana",
        "img_track": "gran_bretana",
        "fastest_lap": "1:27.097",
        "fastest_lap_driver": "Lewis Hamilton",
        "track_length_km": "5.891",
        "last_5_winners": ["Lewis Hamilton", "Lewis Hamilton", "Max Verstappen", "Lewis Hamilton", "Sebastian Vettel"],
        "last_5_poles": ["Carlos Sainz", "Lewis Hamilton", "Max Verstappen", "Lewis Hamilton", "Sebastian Vettel"],
        "fecha": "2023-07-09T22:00:00Z"
    },
    {
        "gp_name": "Gran Premio de Hungría",
        "track_name": "Hungaroring",
        "id_card": "hungria",
        "straights": "45%",
        "slow_turns": "25%",
        "medium_turns": "20%",
        "fast_turns": "10%",
        "boxText": "• Este circuito es conocido por su naturaleza revirada y técnica, siendo comparado a menudo con un circuito urbano permanente.",
        "calendar_date": "2023-07-23",
        "img_country": "hungria",
        "img_track": "hungria",
        "fastest_lap": "1:16.627",
        "fastest_lap_driver": "Max Verstappen",
        "track_length_km": "4.381",
        "last_5_winners": ["Max Verstappen", "Lewis Hamilton", "Esteban Ocon", "Lewis Hamilton", "Lewis Hamilton"],
        "last_5_poles": ["Max Verstappen", "Lewis Hamilton", "Lewis Hamilton", "Valtteri Bottas", "Lewis Hamilton"],
        "fecha": "2023-07-23T22:00:00Z"
    },
    {
        "gp_name": "Gran Premio de Bélgica",
        "track_name": "Circuito de Spa-Francorchamps",
        "id_card": "belgica",
        "straights": "70%",
        "slow_turns": "10%",
        "medium_turns": "10%",
        "fast_turns": "10%",
        "boxText": "• Conocido por su larga recta Kemmel y la icónica sección Eau Rouge-Raidillon, Spa es un favorito entre pilotos y fans.",
        "calendar_date": "2023-07-30",
        "img_country": "belgica",
        "img_track": "belgica",
        "fastest_lap": "1:46.286",
        "fastest_lap_driver": "Valtteri Bottas",
        "track_length_km": "7.004",
        "last_5_winners": ["Max Verstappen", "Max Verstappen", "Lewis Hamilton", "Charles Leclerc", "Sebastian Vettel"],
        "last_5_poles": ["Carlos Sainz", "Max Verstappen", "Lewis Hamilton", "Charles Leclerc", "Sebastian Vettel"],
        "fecha": "2023-07-30T22:00:00Z"
    },
    {
        "gp_name": "Gran Premio de Países Bajos",
        "track_name": "Circuito de Zandvort",
        "id_card": "netherland",
        "straights": "70%",
        "slow_turns": "10%",
        "medium_turns": "10%",
        "fast_turns": "10%",
        "boxText": "• Conocido por su",
        "calendar_date": "2023-07-30",
        "img_country": "netherland",
        "img_track": "netherland",
        "fastest_lap": "1:46.286",
        "fastest_lap_driver": "Valtteri Bottas",
        "track_length_km": "7.004",
        "last_5_winners": ["Max Verstappen", "Max Verstappen", "Lewis Hamilton", "Charles Leclerc", "Sebastian Vettel"],
        "last_5_poles": ["Carlos Sainz", "Max Verstappen", "Lewis Hamilton", "Charles Leclerc", "Sebastian Vettel"],
        "fecha": "2023-07-30T22:00:00Z"
    },
    {
        "gp_name": "Gran Premio de Italia",
        "track_name": "Autodromo Nazionale Monza",
        "id_card": "italia",
        "straights": "75%",
        "slow_turns": "10%",
        "medium_turns": "10%",
        "fast_turns": "5%",
        "boxText": "• Apodado el 'Templo de la Velocidad', Monza es conocido por sus largas rectas y chicanes desafiantes.",
        "calendar_date": "2023-09-03",
        "img_country": "italia",
        "img_track": "italia",
        "fastest_lap": "1:21.046",
        "fastest_lap_driver": "Lewis Hamilton",
        "track_length_km": "5.793",
        "last_5_winners": ["Max Verstappen", "Daniel Ricciardo", "Pierre Gasly", "Charles Leclerc", "Lewis Hamilton"],
        "last_5_poles": ["Max Verstappen", "Max Verstappen", "Charles Leclerc", "Charles Leclerc", "Lewis Hamilton"],
        "fecha": "2023-09-03T22:00:00Z"
    },
    {
        "gp_name": "Gran Premio de Singapur",
        "track_name": "Marina Bay Street Circuit",
        "id_card": "singapur",
        "straights": "50%",
        "slow_turns": "30%",
        "medium_turns": "15%",
        "fast_turns": "5%",
        "boxText": "• Este circuito nocturno urbano es conocido por su exigente naturaleza y alta humedad, haciendo que sea una de las carreras más duras del año.",
        "calendar_date": "2023-09-17",
        "img_country": "singapur",
        "img_track": "singapur",
        "fastest_lap": "1:41.905",
        "fastest_lap_driver": "Lewis Hamilton",
        "track_length_km": "5.063",
        "last_5_winners": ["Max Verstappen", "Lewis Hamilton", "Sebastian Vettel", "Lewis Hamilton", "Sebastian Vettel"],
        "last_5_poles": ["Max Verstappen", "Sebastian Vettel", "Lewis Hamilton", "Lewis Hamilton", "Sebastian Vettel"],
        "fecha": "2023-09-17T22:00:00Z"
    },
    {
        "gp_name": "Gran Premio de Japón",
        "track_name": "Circuito de Suzuka",
        "id_card": "japon",
        "straights": "50%",
        "slow_turns": "15%",
        "medium_turns": "20%",
        "fast_turns": "15%",
        "boxText": "• Suzuka es uno de los circuitos más desafiantes, conocido por su diseño en forma de ocho y sus curvas rápidas y técnicas.",
        "calendar_date": "2023-09-24",
        "img_country": "japon",
        "img_track": "japon",
        "fastest_lap": "1:30.983",
        "fastest_lap_driver": "Valtteri Bottas",
        "track_length_km": "5.807",
        "last_5_winners": ["Max Verstappen", "Valtteri Bottas", "Lewis Hamilton", "Lewis Hamilton", "Sebastian Vettel"],
        "last_5_poles": ["Max Verstappen", "Sebastian Vettel", "Lewis Hamilton", "Lewis Hamilton", "Sebastian Vettel"],
        "fecha": "2023-09-24T22:00:00Z"
    },
    {
        "gp_name": "Gran Premio de Catar",
        "track_name": "Circuito Internacional de Losail",
        "id_card": "catar",
        "straights": "60%",
        "slow_turns": "15%",
        "medium_turns": "15%",
        "fast_turns": "10%",
        "boxText": "• Este circuito nocturno es conocido por sus largas rectas y curvas de media y alta velocidad.",
        "calendar_date": "2023-10-08",
        "img_country": "catar",
        "img_track": "catar",
        "fastest_lap": "1:22.162",
        "fastest_lap_driver": "Lewis Hamilton",
        "track_length_km": "5.380",
        "last_5_winners": ["Lewis Hamilton"],
        "last_5_poles": ["Lewis Hamilton"],
        "fecha": "2023-10-08T22:00:00Z"
    },
    {
        "gp_name": "Gran Premio de Estados Unidos",
        "track_name": "Circuito de las Américas",
        "id_card": "usa",
        "straights": "50%",
        "slow_turns": "20%",
        "medium_turns": "20%",
        "fast_turns": "10%",
        "boxText": "• Este circuito en Austin es conocido por su primera curva en cuesta y su variado diseño que combina secciones técnicas y de alta velocidad.",
        "calendar_date": "2023-10-22",
        "img_country": "usa",
        "img_track": "usa",
        "fastest_lap": "1:36.169",
        "fastest_lap_driver": "Charles Leclerc",
        "track_length_km": "5.513",
        "last_5_winners": ["Max Verstappen", "Max Verstappen", "Valtteri Bottas", "Kimi Raikkonen", "Lewis Hamilton"],
        "last_5_poles": ["Carlos Sainz", "Max Verstappen", "Valtteri Bottas", "Lewis Hamilton", "Lewis Hamilton"],
        "fecha": "2023-10-22T22:00:00Z"
    },
    {
        "gp_name": "Gran Premio de México",
        "track_name": "Autódromo Hermanos Rodríguez",
        "id_card": "mexico",
        "straights": "55%",
        "slow_turns": "15%",
        "medium_turns": "20%",
        "fast_turns": "10%",
        "boxText": "• Este circuito en Ciudad de México es conocido por su altitud, lo que afecta el rendimiento de los coches.",
        "calendar_date": "2023-10-29",
        "img_country": "mexico",
        "img_track": "mexico",
        "fastest_lap": "1:17.774",
        "fastest_lap_driver": "Max Verstappen",
        "track_length_km": "4.304",
        "last_5_winners": ["Max Verstappen", "Lewis Hamilton", "Max Verstappen", "Lewis Hamilton", "Max Verstappen"],
        "last_5_poles": ["Max Verstappen", "Lewis Hamilton", "Max Verstappen", "Sebastian Vettel", "Max Verstappen"],
        "fecha": "2023-10-29T22:00:00Z"
    },
    {
        "gp_name": "Gran Premio de Brasil",
        "track_name": "Autódromo José Carlos Pace",
        "id_card": "brasil",
        "straights": "50%",
        "slow_turns": "20%",
        "medium_turns": "20%",
        "fast_turns": "10%",
        "boxText": "• También conocido como Interlagos, este circuito es famoso por su configuración técnica y su ambiente apasionado.",
        "calendar_date": "2023-11-05",
        "img_country": "brasil",
        "img_track": "brasil",
        "fastest_lap": "1:10.540",
        "fastest_lap_driver": "Max Verstappen",
        "track_length_km": "4.309",
        "last_5_winners": ["George Russell", "Lewis Hamilton", "Max Verstappen", "Lewis Hamilton", "Sebastian Vettel"],
        "last_5_poles": ["Kevin Magnussen", "Lewis Hamilton", "Max Verstappen", "Lewis Hamilton", "Valtteri Bottas"],
        "fecha": "2023-11-05T22:00:00Z"
    },
    {
        "gp_name": "Gran Premio de Las Vegas",
        "track_name": "Circuito Urbano de Las Vegas",
        "id_card": "las_vegas",
        "straights": "60%",
        "slow_turns": "20%",
        "medium_turns": "10%",
        "fast_turns": "10%",
        "boxText": "• Este nuevo circuito urbano recorrerá las calles de Las Vegas, prometiendo una emocionante carrera nocturna.",
        "calendar_date": "2023-11-18",
        "img_country": "las_vegas",
        "img_track": "las_vegas",
        "fastest_lap": "",
        "fastest_lap_driver": "",
        "track_length_km": "6.120",
        "last_5_winners": [],
        "last_5_poles": [],
        "fecha": "2023-11-18T22:00:00Z"
    },
    {
        "gp_name": "Gran Premio de Abu Dabi",
        "track_name": "Circuito Yas Marina",
        "id_card": "abu_dabi",
        "straights": "55%",
        "slow_turns": "20%",
        "medium_turns": "10%",
        "fast_turns": "10%",
        "boxText": "• Este circuito introducido a principios del siglo XX1, promete siempre un espectáculo siendo el sitio donde grandes pilotos se han coronado como campeones del mundo.",
        "calendar_date": "2023-11-18",
        "img_country": "abu_dabi",
        "img_track": "abu_dabi",
        "fastest_lap": "",
        "fastest_lap_driver": "",
        "track_length_km": "6.120",
        "last_5_winners": [],
        "last_5_poles": [],
        "fecha": "2023-11-18T22:00:00Z"
    }
]


var race_number = 0;
//Eliminamos los grandes premios que no se van a correr.
race_calendar.forEach(element => {
    if ( (element.fecha==undefined) || (element.fecha == "")) {
        race_calendar.pop(element)
    }
});
// Ordenamos por fecha
race_calendar.sort((a, b) => new Date(a.fecha) - new Date(b.fecha));
// console.table(race_calendar)
//Leer los datos de cada tablita.
race_calendar.forEach(element => {
    console.info(element.gp_name,", ",element.track_name)
});



